name: Terraform Infrastructure Tests

on:
  push:
    branches:
      - main
    paths:
      - 'infra/**'
      - '.github/workflows/terraform-test.yml'
  pull_request:
    paths:
      - 'infra/**'
      - '.github/workflows/terraform-test.yml'

env:
  TF_VERSION: 1.12.2

jobs:
  terraform-validate:
    name: Terraform Validation
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infra
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Format and Validate Terraform
        run: |
          terraform fmt -check -recursive
          terraform init -backend=false
          terraform validate
