name: Terraform Infrastructure Tests

on:
  push:
    branches:
      - main
    paths:
      - 'infra/**'
      - '.github/workflows/terraform-test.yml'
  pull_request:
    paths:
      - 'infra/**'
      - '.github/workflows/terraform-test.yml'

env:
  TF_VERSION: 1.12.2

jobs:
  terraform-validate:
    name: Terraform Validation
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infra
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Format and Validate Terraform
        run: |
          terraform fmt -check -recursive
          terraform init -backend=false
          terraform validate

  terraform-security-scan:
    name: Terraform Security Scan
    runs-on: ubuntu-latest
    needs: terraform-validate
    defaults:
      run:
        working-directory: ./infra
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Init Terraform
        run: terraform init -backend=false

      - name: Run Checkov Security Scan
        uses: bridgecrewio/checkov-action@master
        with:
          directory: ./infra
          framework: terraform
          output_format: sarif
          output_file_path: ./checkov-results.sarif

      - name: Upload Checkov Results
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: ./checkov-results.sarif
